# Local server
server:
  # port is used by spring-boot-admin
  port: 8080
  contextPath: /arduinoob
spring:
  datasource:
    password: Gr1m7h0RG@raiTH903
    url: jdbc:mysql://localhost:3306/arduinoobdb?user=root